# UR5 DOCKER INSTALALTION

FROM ros_base:latest

# UR library required
RUN apt-get install -y ros-noetic-ur-client-library && \ 
    apt-get install -y ros-noetic-industrial-robot-status-interface && \ 
    apt-get install -y ros-noetic-ur-msgs && \ 
    apt-get install -y ros-noetic-tf2-bullet && \ 
    apt-get install -y ros-noetic-scaled-joint-trajectory-controller && \ 
    apt-get install -y ros-noetic-speed-scaling-interface && \ 
    apt-get install -y ros-noetic-speed-scaling-state-controller && \ 
    apt-get install -y ros-noetic-pass-through-controllers && \ 
    apt-get install -y ros-noetic-gazebo-ros-control &&\
    apt-get install -y ros-noetic-robot && \
    apt-get install -y ros-noetic-trac-ik
 




