version: "3"
services:
  rightarm:
    image: universalrobots/ursim_e-series
    environment:
      - ROBOT_MODEL=UR10
    networks:
      ursim_net:
        ipv4_address: 10.5.0.5
    volumes:
      - ./ursim/urcaps:/urcaps
      - ./ursim/programs_rightarm:/ursim/programs
  leftarm:
    image: universalrobots/ursim_e-series
    environment:
      - ROBOT_MODEL=UR3
    networks:
      ursim_net:
        ipv4_address: 10.5.0.6
    volumes:
      - ./ursim/urcaps:/urcaps
      - ./ursim/programs_leftarm:/ursim/programs

networks:
  ursim_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
